/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

export interface NavigateToOptions {
  url: "/pages/index" |
       "/pages/hi" |
       "/pages/invoiceList" |
       "/pages/lookUp" |
       "/pages/lookUpAdd" |
       "/pages/merchant" |
       "/pages/scanCode" |
       "/pages/unionPay" |
       "/pages/webview" |
       "/pages/whatMerchant" |
       "/pages/issue/detail" |
       "/pages/issue/index" |
       "/pages-sub/index";
}
interface RedirectToOptions extends NavigateToOptions {}

export interface SwitchTabOptions {
  
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
